spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/dowit_task_db
spring.datasource.username=jaeytea
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true
app.jwt.secret=dowit-super-secret-key-must-be-32-chars-min-2024
app.jwt.expiration=86400000